#! /bin/sh

#startup
xrandr --setprovideroutputsource modesetting NVIDIA-0
xrandr --auto
xrandr --dpi 96

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor eDP-1-1  -d I II III IV V
bspc monitor HDMI-1-1 -d VI VII VIII IX X
bspc monitor -g 1920x1080+0+0
bspc config border_width         0 
bspc config window_gap          20

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer   true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

~/.screenlayout/screenlayout.sh
~/.config/polybar/launch.sh
picom -b &
nm-applet &
