#!/bin/bash

# xrandr --setprovideroutputsource modesetting NVIDIA-0
# xrandr --auto
# xrandr --dpi 96

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI
bspc monitor HDMI-1 -d VII VIII IX

bspc config border_width         0
bspc config window_gap          20

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled

~/.config/bspwm/startup.sh

# ~/.screenlayout/layout.sh
# ~/.config/polybar/launch.sh
# ~/.fehbg &
# xsetroot -cursor_name left_ptr
# xinput --set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1
# picom -b
# picom -b --experimental-backends
#
# mangkoran's startup apps
# redshift &
# unclutter --timeout 2 &
#
# discord &
# telegram-desktop &
#
# sleep 1 && ~/.config/polybar/launch.sh
